setwd("/home/anisha/Downloads/exdata_data_household_power_consumption")
data <- read.table("household_power_consumption.txt", sep = ';', na.strings = "?", stringsAsFactors=F, header = T)
data_sub <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
png("plot1.png", width = 480, height = 480)
hist(data_sub$Global_active_power, xlab = "Global Active Power(kilowatts)", ylab = "Frequency", main = "Global Active Power", col = "red")
dev.off()