setwd("/home/anisha/Downloads/exdata_data_household_power_consumption")
data <- read.table("household_power_consumption.txt", sep = ';', na.strings = "?", stringsAsFactors=F, header = T)
data_sub <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
png("plot2.png", width = 480, height = 480)
data_time_date <-paste(data_sub$Time, data_sub$Date, sep=" ")
data_time_date <- strptime(data_time_date, "%H:%M:%S %d/%m/%Y")
plot(data_time_date, data_sub$Global_active_power, xlab = "", ylab = "Global Active Power(kilowatts)", type = "l")
dev.off()